type Person {
  id: ID!
  name: String
  birthYear: String
  eyeColor: String
  gender: String
  hairColor: String
  height: Int
  mass: Float
  skinColor: String
  homeworld: Planet
  species: Species
  filmConnection: PersonFilmsConnection
  starshipConnection: PersonStarshipConnection
  vehicleConnection: PersonVehiclesConnection
  created: String
  edited: String
}
